### PR TITLE
Let desktop file fit openSUSE rules

### LINKED ISSUE #68: openSUSE packaging issues
Hello!

There are some distro specific build errors: first of all  GenericName tag has to be provided for desktop files, the second one is insufficient desktop file Category (see https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories f.e.).
And finally:
[   46s] ... running 02-check-gcc-output
[   46s] ... testing for serious compiler warnings
[   46s]     (using /usr/lib/build/checks-data/check_gcc_output)
[   46s]     (using /var/tmp/build-root/openSUSE_13.2-x86_64/.build.log)
[   46s] 
[   46s] I: A function uses a 'return;' statement, but has actually a value
[   46s]    to return, like an integer ('return 42;') or similar.
[   46s] W: xfdashboard voidreturn viewpad.c:511, 512, 513

Any tips please?

### PR DESCRIPTION
**Pull request by DAP-DarkneSS**
It finally resolves #68.

### CODE REVIEW

**Comment by gmc-holle** [comment]
Thanks for the patch and the pull request. But I have one question: Will you still comply to the openSUSE rules if your patch would only change the "Categories" line in desktop file?

The reason is that I read that xfdashboard work in many other desktop environments like openbox, lxde and so on. Even if xfdashboard is very much related to Xfce I wouldn't like to get it unlisted in other desktop environments except for at least Gnome and Unity which have their own "Gnome-shell like dashboards". I think KDE is also a candidate and that why it is listed in "NotShowIn".

**Comment by DAP-DarkneSS** [comment]
Yes, of course, but main Category will have to be not System. I'll revert this commit and will add another suitable category. Will it be OK?

**Comment by gmc-holle** [comment]
Of course, that's ok.

**Comment by DAP-DarkneSS** [comment]
openSUSE how to instll link: http://software.opensuse.org/download.html?project=X11%3Axfce&package=xfdashboard

**Comment by gmc-holle** [comment]
It looks like that finding one or more good categories that also fit the purpose of the application is really hard :(

What do you think of changing the categories to ```GTK;Utility;```? Or is ```System;GTK;Filesystem;FileTools;" better?

**Comment by DAP-DarkneSS** [comment]
Filesystem;FileTools; is a lie imho. Single Utility; isn't sufficient because subcategory isn't provided.

**Comment by gmc-holle** [comment]
Ahh .... my mistake. Forget it. It includes "Applet" again which forces using "OnlyShowIn" again :(

**Comment by DAP-DarkneSS** [comment]
As already mentioned before and as also pull request provides the same diff if fix the build error but introduces a post-build warning: xfdashboard: W: invalid-desktopfile /usr/share/applications/xfdashboard.desktop value item "Applet" in key
"Categories" in group "Desktop Entry" is a reserved category, so a "OnlyShowIn" key must be included.
Of course package is build fine and it is published for users ;)

**Comment by DAP-DarkneSS** [comment]
Don't worry too much. Freedesktop make all f.e. LXDE tools introduce the  
same warning because there are no registered OnlyShownIn key for LXDE.

**Comment by gmc-holle** [comment]
Thanks for your help and your patience to explain it to me :) I really appreciate it.

But what it the accepted way to handle this pull request? As far as I can see and I understood you fixed this problem with your "spec" file and package. Should I just close this request?

Sorry for the stupid question but it's my first pull request at all ;)

**Comment by DAP-DarkneSS** [comment]
No worries. It was an interesting study for me too.
If you like the diff you could just press a magic green button on top of comment writing widget. If no just close. I've never gotten pull request so it a kind of theory.

**Comment by gmc-holle** [comment]
Thanks again and thanks for packaging for openSUSE :)

I will at least fix the "GenericName" warning ;)

**Pull request closed without merging**
